kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-sample-pipeline"
spec:
  source:
    git:
      uri: https://github.com/garbagego/pipeline.git
  strategy:
    jenkinsPipelineStrategy: 
      jenkinsfilePath: jenkins/jenkinsfile
