kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-sample-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: 
        jenkinsfilePath: jenkins/jenkinsfile
      type: JenkinsPipeline
